# Generated by Django 3.2.5 on 2021-09-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='User_contact',
        ),
    ]
